matuck_george_grant_co:
    resource: "@matuckGeorgeGrantCoBundle/Controller"
    type:     annotation
    prefix:   /

liip_theme:
        resource: "@LiipThemeBundle/Resources/config/routing.xml"
        prefix: /theme

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"